### ISSUE TITLE
Write an example program

### ISSUE THREAD

**Issue by QubeGames** [SW4-P4/Report#10]
Lav metabeskrivelse af vores eget sprog

**Comment by EmilieSonne** [comment]
Et forslag: vi kunne forsøge simpelthen at beskrive forskellige tandhjul i "natural language" og se, om vi kan organisere det som kode - altså bare tage udgangspunkt i nogle billeder af nogle forskellige tandhjul, og så prøve at beskrive dem og så se, hvad det fører til. Så kommer vi måske i nærheden af, hvordan det er "intuitivt" at beskrive et tandhjul. Hvis vi ville være mega cool, kunne vi også prøve at lave et lille questionnaire med fx 3-10 signifikant forskellige tandhjul, og så få familie/venner/strangers til at beskrive dem.
